alexandria:
  info:
    service: "author"
    version: 1.0.0
  persistence:
    dbms:
      url: "postgres://postgres:root@0.0.0.0:5432/alexandria-author?sslmode=disable"
      driver: "postgres"
      user: "postgres"
      password: "root"
      host: "0.0.0.0"
      port: 5432
      database: "alexandria-author"
    mem:
      network: ""
      host: "0.0.0.0"
      port: 6379
      password: ""
      database: 0
  service:
    transport:
      http:
        host: "0.0.0.0"
        port: 8080
      rpc:
        host: "0.0.0.0"
        port: 31337