alexandria:
  info:
    service: "event-watcher"
    version: 0.1.0
  persistence:
    doc:
      collection: "ALEXANDRIA_EVENT_WATCHER"
      partition_key: "watcher_id"
  service:
    transport:
      http:
        host: "0.0.0.0"
        port: 8080
      rpc:
        host: "0.0.0.0"
        port: 31337
  tracing:
    # OpenTracing consumers
    zipkin:
      host: "http://zipkin:9411/api/v2/spans"
      endpoint: "0.0.0.0:8080"
      bridge: true
  event:
    kafka:
      cluster:
        # Kafka Brokers nodes
        leader:
          host: "kafka"
          port: 9092
        1:
          host: "kafka1"
          port: 9092