alexandria:
  info:
    service: "identity"
    version: 0.1.0
  persistence:
    mem:
      network: ""
      host: "redis"
      port: 6379
      password: ""
      database: 0
  service:
    transport:
      http:
        host: "0.0.0.0"
        port: 8080
      rpc:
        host: "0.0.0.0"
        port: 31337
  tracing:
    # OpenTracing/OpenCensus consumers
    zipkin:
      host: "http://zipkin:9411/api/v2/spans"
      endpoint: "0.0.0.0:8080"
      bridge: true
  eventbus:
    kafka:
      brokers:
        # Kafka Brokers nodes
        - "kafka:9092"
  cloud:
    aws:
      cognito:
        pool: "cognito_pool_id"
        client: "cognito_pool_secret_key"
  security:
    auth:
      jwt:
        secret: "example_secret_key"
