alexandria:
  info:
    service: "identity"
    version: 0.1.0
  persistence:
    dbms:
      url: "postgres://postgres:root@localhost:5432/alexandria_identity?sslmode=disable"
      driver: "postgres"
      user: "postgres"
      password: "root"
      host: "postgres"
      port: 5432
      database: "alexandria_identity"
    mem:
      network: ""
      host: "localhost"
      port: 6379
      password: ""
      database: 0
  service:
    transport:
      http:
        host: "0.0.0.0"
        port: 8080
      rpc:
        host: "0.0.0.0"
        port: 31337
  tracing:
    # OpenTracing consumers
    zipkin:
      host: "http://zipkin:9411/api/v2/spans"
      endpoint: "0.0.0.0:8080"
      bridge: true
  event:
    kafka:
      cluster:
        # Kafka Brokers nodes
        leader:
          host: "kafka"
          port: 9092
        1:
          host: "kafka1"
          port: 9092
  cloud:
    aws:
      cognito:
        pool: "us-east-1_12iAEifyh"
        client: "37njo8eviv33br7u2cmbbs1sbp"
  security:
    auth:
      jwt:
        secret: "example_secret_key"
