alexandria:
  info:
    version: 1.0.0
  persistence:
    dbms:
      url: "postgres://postgres:root@localhost/alexandria-media?sslmode=disable"
    mem:
      host: "localhost:6379"
      password: ""
  service:
    delivery:
      http:
        port: :8080
      rpc:
        port: :31337
