alexandria:
  info:
    service: "category"
    version: 0.1.0
  persistence:
    cassandra:
      username: ""
      password: ""
      keyspace: "alexa1"
      cluster:
        ## Cassandra distributed nodes hosts
        - "localhost"
    mem:
      network: ""
      host: "redis"
      port: 6379
      password: ""
      database: 0
  service:
    transport:
      http:
        host: "0.0.0.0"
        port: 8080
      rpc:
        host: "0.0.0.0"
        port: 31337
  tracing:
    # OpenTracing/OpenCensus consumers
    zipkin:
      host: "http://zipkin:9411/api/v2/spans"
      endpoint: "0.0.0.0:8081"
      bridge: true
  eventbus:
    kafka:
      brokers:
        # Kafka Brokers nodes
        - "localhost:9092"