alexandria:
  info:
    service: "media"
    version: 1.0.0
  persistence:
    dbms:
      url: "postgres://postgres:root@postgres:5432/alexandria_media?sslmode=disable"
      driver: "postgres"
      user: "postgres"
      password: "root"
      host: "postgres"
      port: 5432
      database: "alexandria_media"
    mem:
      network: ""
      host: "redis"
      port: 6379
      password: ""
      database: 0
  service:
    transport:
      http:
        host: "0.0.0.0"
        port: 8080
      rpc:
        host: "0.0.0.0"
        port: 31337
    metric:
      zipkin:
        host: "http://zipkin:9411/api/v2/spans"
        endpoint: "0.0.0.0:8080"
        bridge: true